### ISSUE TITLE
Could the code be used with OpenBCI headset?

### ISSUE THREAD

**Issue by JPLeRouzic** [fwillett/speechBCI#4]
Dear professor Willet,

I understand this code was intended to be used with devices implanted deep in the brain, but I wonder (stupid question indeed) what kind of results would be obtained with a surface EEG headset such as those from OpenBCI?

Some problems I am aware as a lay person:
* Your code uses 128 deep brain electrodes while surface EEG headsets have 8 to 32 channels.
* Using surface EEG means bad electrical contact (especially through hair) and lot of noise.
* It seems to me that your patients had to train the RNN roughly 100 hours, if data is of much lower quality this means much longer training time, which would defeat the purpose for ALS patients as some of them do not live much longer.
* Even EEG headsets are costly (thousands dollars). 

Thank you for having read this question.

Jean-Pierre Le Rouzic
https://padiracinnovation.org/News

**Comment by fwillett** [comment]
Hi Jean-Pierre, thank you for your question! I doubt EEG signals can yield this level of performance, which is why we are exploring intracortical microelectrode arrays. Historically, EEG signals have yielded a much lower signal-to-noise ratio for decoding motor behaviors. As for training time, this is an active area of research and I believe training times will continue to decrease with further algorithm developments and improvements to the recording devices (e.g., more channels) which will yield even higher SNRs. Note that we used about 10 hours of data in the study, not 100.
